# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191124_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='download.jpg', upload_to='profiles/'),
        ),
    ]
