# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='profiles/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
    ]
