# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20191123_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='landing_page',
            field=models.ImageField(null=True, upload_to='landing/'),
        ),
    ]
