# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20191123_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(max_length=255),
        ),
    ]
