# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-24 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20191124_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='prefname',
            new_name='nickname',
        ),
    ]
